image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
    - init: |
          clj -X:deps prep
    - command : |
        clojure -M -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
